<?php


namespace Mishusoft\Ema\UrlSplitters;


use Mishusoft\Framework\Chipsets\Services\SecureDataTransferService;

class ApplicationProgrammingInterface extends SecureDataTransferService
{
    public function __construct()
    {
        parent::__construct();
    }

    public function api(array $request)
    {
        parent::api($request); // TODO: Change the autogenerated stub
    }

    public function monitor(array $request)
    {
        parent::monitor($request); // TODO: Change the autogenerated stub
    }
}