---
browsers:
- analysers
- applications
- browsers
- browsers-engines
- bots
- compatibilities
- cloud-platforms
- email-clients
- feed-readers
- multimedia-players
- offline-browsers
- tools
devices:
- categories
platforms:
- architectures
- os
- wm
resources:
- analysers
- applications
- authors
- bots
- browsers
- browsers-engines
- compatibilities
- cloud-platforms
- devices
- email-clients
- feed-readers
- licences
- multimedia-players
- offline-browsers
- platforms
- tools
- wm
...
