---
name: Mishusoft Packages Manager
version: 1.0.0
packages:
  default: Ema
  all:
  - Ema
loader:
  Ema: Ema.Loader.php
modules:
  Ema:
    default: Main
    all:
      Main:
        status: enable
config:
  database:
    activation: true
...
