<article class="ms-app">
    <ms-app-body class="ms-app-body width-1024px flex-center-left">
        <ms-app-about class="protect document-20px flex-column">
            <ms-app-about-title
                    style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;color:#ffffff;margin-top: 10px;text-align: left;font-size: 16px;height: auto;width: inherit;display: flex;flex-direction: row;">
                <span style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;display: flex;flex-direction: row;margin-left: 10px;justify-content:center;align-items:center;"><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 40px;font-weight: bold;">Who We Are</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 40px;font-weight: bold;">|</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 18px;font-weight: normal;">Basic Information</span></span>
            </ms-app-about-title>
            <ms-app-about-content
                    style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;color:white;/*! margin-top: 20px; */text-align: left;font-size: 16px;height: auto;width: inherit;display: flex;flex-direction: column;/*! background: http: //localhost/media/images/icons/companies/Custom-Software-Development.png; *//*! border-radius: 10px; *//*! box-shadow: 0 3px 4px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24); *//*! background-attachment: http: //localhost/media/images/icons/companies/Custom-Software-Development.png; *//*! background-image: url(http://localhost/media/images/icons/companies/Custom-Software-Development.png); */background-repeat: no-repeat;background-size: 100% 500px;">
                <item style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;color:inherit;/*! background: white; *//*! margin-bottom:10px; */padding: 20px 10px 20px 10px;/*! border-radius:10px; */text-align: left;height: auto;width: auto;/*! box-shadow: 0 3px 4px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24); */display: flex;flex-direction: column;">
                    <span style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 14px;font-weight: normal;line-height: 1.5;margin-top: 5px;text-align: justify;">Mishusoft Systems Incorporated is a software development company that is going to be established with a view to offering quality IT solutions at home and abroad. The company is keen to take the advantage of fast growing global software and data processing industry by offering professional service and price for support and benefit of the valued customers.</span>
                </item>
                <item style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;color:inherit;/*! background: white; */margin-bottom:10px;padding: 20px;/*! border-radius:10px; */text-align: left;height: auto;width: auto;/*! box-shadow: 0 3px 4px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24); */display: flex;flex-direction: column;">
                    <span style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 22px;font-weight: bold;margin-bottom:5px;text-transform: uppercase;border-bottom: 5px solid #9932CC;background: #E1B4F7;padding-left: 5px;color: #9932CC;">Our History</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 14px;font-weight: normal;line-height: 1.5;margin-top: 5px;text-align: justify;">Mishusoft Systems Incorporated is a software development company that is going to be established with a view to offering quality IT solutions at home and abroad. The company is keen to take the advantage of fast growing global software and data processing industry by offering professional service and price for support and benefit of the valued customers.</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 15px;font-weight: normal;line-height: 1.6;margin-top: 5px;text-align: justify;">Mishusoft Systems Incorporated has started its journey to provide quality output and they are well linked internationally. Mishusoft Systems Incorporated has unique and holistic approaches toward continuous improvement through training and development of human resources to adapt into the market aiming to meet the demands of client and keep them constant touch with the latest global technological development. Mishusoft Systems Incorporated. IT is striving to provide a cost effective and high standard services in the dynamic IT industry. The company would build itself with a strategy of continuous reeducation and motivation to create an innovative and dedicated work force in the expanding IT sector.</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 15px;font-weight: normal;line-height: 1.6;margin-top: 5px;text-align: justify;">Mishusoft Systems Incorporated especially aims at export oriented software development. Thus Mishusoft Systems Incorporated it industry is growing at a higher rate and opening opportunities of service linkage to professional service providers all over the world.</span>
                </item>
                <item style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;color:inherit;/*! background: white; */margin-bottom:10px;padding: 20px;border-radius:10px;text-align: left;height: auto;width: auto;/*! box-shadow: 0 3px 4px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24); */display: flex;flex-direction: column;">
                    <span style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 20px;font-weight: bold;margin-bottom:5px;">Our Responsibilities</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 15px;font-weight: normal;line-height: 1.6;margin-top: 5px;text-align: justify;">Mishusoft Systems Incorporated has main support office at Mirpur (Dhaka) in the country. Its main responsibility and duty  are to provide ICT solutions in the field of enterprise software solutions, design, development, maintenance services, customize software, Data entry, web solution, government sectors to supply, install, maintain, operate, manage data processing and information systems etc. The Company is equipped with most modem and sophisticated machinery and equipment, which was procured from local market at competitive price run by a highly trained and skilled manpower. The firm is self-sufficient having a continuous trouble free operation ensuring timely deliver, of its product to foreign countries via modem satellite communication system. The Company is providing all sorts of policy and infrastructure support also.</span>
                </item>
                <item style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;color:inherit;/*! background: white; */margin-bottom:10px;padding: 20px;border-radius:10px;text-align: left;height: auto;width: auto;/*! box-shadow: 0 3px 4px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24); */display: flex;flex-direction: column;">
                    <span style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 20px;font-weight: bold;margin-bottom:5px;">Our Philosophy</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 15px;font-weight: normal;line-height: 1.6;margin-top: 5px;text-align: justify;">Mishusoft Systems Incorporated believes that Bangladesh can play an important role in the international IT markets. Thus, we shall contribute to the realization of a sustainable society through continuous technological innovation and advancement.</span>
                </item>
                <item style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;color:inherit;/*! background: white; */margin-bottom:10px;padding: 20px;border-radius:10px;text-align: left;height: auto;width: auto;/*! box-shadow: 0 3px 4px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24); */display: flex;flex-direction: column;">
                    <span style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 20px;font-weight: bold;margin-bottom:5px;">Our Objectives</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 15px;font-weight: normal;line-height: 1.6;margin-top: 5px;text-align: justify;">Our objectives are to maximize its local and international customer’s productivity and profitability by providing IT services both in hardware integration, ERP Solution, Customize software development and deployment services in an innovative manner.</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 15px;font-weight: normal;line-height: 1.6;margin-top: 5px;text-align: justify;">We have experienced professionals who are ready with indomitable commitment to cater any IT product and services viewing to transform The Concept into Reality”</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 15px;font-weight: normal;line-height: 1.6;margin-top: 5px;text-align: justify;">We delivered number of successful, most innovative and cost-effective and efficient technical solution for both home and abroad for a number of global companies, SME sector, Government agencies where we have bank our success.</span>
                </item>
                <item style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;color:inherit;/*! background: white; */margin-bottom:10px;padding: 20px;border-radius:10px;text-align: left;height: auto;width: auto;/*! box-shadow: 0 3px 4px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.24); */display: flex;flex-direction: column;">
                    <span style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 20px;font-weight: bold;margin-bottom:5px;">Our Mission</span><span
                            style="text-decoration: none;border-style: none;user-select: none;-webkit-user-select: none;-ms-user-select: none;outline-style: none;font-size: 15px;font-weight: normal;line-height: 1.6;margin-top: 5px;text-align: justify;">Our Mission is “to provide efficient business value and optimized solutions needed by our clients thus finally we improve our stakeholders’ quality of life.”</span>
                </item>
            </ms-app-about-content>
        </ms-app-about>
    </ms-app-body>
</article>
