<?php


namespace Mishusoft\Framework\Chipsets\Http\UserAgents;


use Mishusoft\Framework\Chipsets\Http\UserAgents;

class Developers extends UserAgents
{

    public function list(): array
    {
        // TODO: Implement list() method.
        return [
            "10betterpages GmbH",
            "115.com",
            "2345.com",
            "8pecxstudios",
            "A6 Corp",
            "abonti.com",
            "Access",
            "AdaptiveBee SASU",
            "adbeat.com",
            "AddThis.com",
            "Adobe Systems Incorporated",
            "adscanner.tv",
            "AgileBits, Inc.",
            "Ahrefs Pte Ltd",
            "AirWatch LLC",
            "Alexa Internet, Inc",
            "Alexander Clauss",
            "Aliaksandr Valialkin",
            "Alibaba",
            "Aloha Mobile Ltd",
            "alphaseobot.com",
            "Amazon.com, Inc.",
            "America Online, Inc.",
            "Anders Pink",
            "Anderson Che",
            "Andrew Horton",
            "Antonio Davide",
            "AOL",
            "Apple Inc",
            "APUS-Group",
            "archive.org",
            "ArchiveTeam",
            "Ashrising Phoenixes",
            "Ask.com",
            "aspiegel.com",
            "Astute Solutions",
            "Atsushi Jike",
            "Automattic",
            "Avant Force",
            "AVAST Software s.r.o.",
            "Avira Operations GmbH & Co. KG.",
            "Axandra GmbH",
            "Baidu",
            "Beamrise Team",
            "begun.ru",
            "Beonex Business Services",
            "Bibliotheque nationale de France",
            "Blackboard Inc.",
            "Blekko Inc.",
            "Blizzard Entertainment Inc",
            "bloglovin.com",
            "Bloop S.R.L.",
            "Blue Link Labs",
            "BoardReader",
            "Bot Revolt",
            "BrandVerity",
            "BRAVO UNICORN PTE LTD",
            "Bromium",
            "browsershots.org",
            "browserspy.dk",
            "browzar.com",
            "Callpod Inc.",
            "Cameron Kaiser",
            "capture.heartrails.com",
            "Catchpoint Systems, Inc.",
            "Cent Studio",
            "CheckMark Network",
            "checksite.us",
            "Chedot.com",
            "Cheetah Mobile",
            "Christian Dywan",
            "Christian Noon",
            "cincrawdata.net/bot/",
            "Clickagy",
            "Cloud System Networks",
            "CloudFlare, Inc.",
            "CloudMosa Inc.",
            "Coc Coc Company Limited",
            "CommonCrawl Foundation",
            "Comodo Group Inc",
            "Compuware Corporation",
            "comScore, Inc.",
            "Core Inc",
            "Corey Donohoe",
            "CrazyBrowser.com",
            "crazywebcrawler.com",
            "cstking",
            "Cxense ASA",
            "DareBoost",
            "Dassault Systemes",
            "Datagnion GmbH",
            "datasift.com",
            "Daum Communications Corp",
            "David Frank",
            "David Rosca and Community",
            "Deepnet Security",
            "Digital Millennium Copyright Act Services Ltd.",
            "Diglo Inc",
            "Digola",
            "Diigo, Inc.",
            "Discord",
            "DocBase",
            "DomainSigma",
            "DomainSONO",
            "Domainstats International AB",
            "DomainTools",
            "Dr. Manfred Schauer",
            "DuckDuckGo",
            "easou.com",
            "Easy-Thumb.net",
            "Echobox Limited",
            "Elbert Alias",
            "elefent.eu",
            "Element Software",
            "embed.ly",
            "Entireweb Sweden AB",
            "Ericsson Research",
            "eVenture Capital Partners II, LLC",
            "Evernote Corporation",
            "everyfeed.com",
            "eXenSa",
            "Experian Ltd",
            "Fabien Coeurjoly",
            "Facebook",
            "Faveeo SA",
            "FCCN",
            "FeedBlitz.com",
            "feedly.com",
            "Feng Shen",
            "Fenrir Inc",
            "FlashPeak Inc",
            "Flipboard, Inc.",
            "Florian Bruhin",
            "FREE SAS",
            "Free Software Foundation, Inc.",
            "gadu-gadu.pl",
            "",
            "Genieo",
            "Geometry OU",
            "GESKIMO SRL",
            "getintent.com",
            "Ghost Inspector",
            "gigablast.com",
            "Github",
            "Google Inc",
            "Gordon Lyon",
            "Grammarly Inc.",
            "Grapeshot Limited",
            "Greg Lindahl",
            "GroupHigh LLC",
            "GTmetrix",
            "Guangzhou Network",
            "Handspring",
            "Hans Hasselberg",
            "Hatena Co., Ltd.",
            "Headbanging Sasquatches",
            "Heartlass, Inc.",
            "HiQPdf Software",
            "HJ van Rantwijk",
            "Houzz Inc",
            "HP",
            "HTC",
            "http://law.di.unimi.it",
            "Huawei",
            "HubPages Inc.",
            "HubSpot, Inc.",
            "Hytto Ltd.",
            "IBM",
            "Ichiro",
            "Idee Inc.",
            "iLegendSoft, Inc.",
            "Imagine Easy Solutions, LLC",
            "Impact Tech, Inc",
            "infegy.com",
            "Information Technology Organization of Iran",
            "Infraware Inc",
            "Installatron LLC.",
            "Integral Ad Science, Inc",
            "Intel Corporation",
            "Internet Memory Research",
            "Iridium Browser Team",
            "iterate GmbH",
            "Itteco",
            "Jaime Iniesta",
            "James Hurst",
            "Jaohawi AB",
            "Jeanfrancois Arcand",
            "Jobboerse.com",
            "Jolla Ltd.",
            "Jonas Genannt (HggH)",
            "Kakao Corp",
            "Kawe Apps",
            "Kaylon Technologies",
            "kbclub",
            "KDE e.V.",
            "Keanu Lee",
            "Kerverus IT Ltd",
            "Kingsoft",
            "kinza.jp",
            "Kitsuregawa Laboratory, The University of Tokyo",
            "KKBOX Taiwan Co., Ltd.",
            "kmeleonbrowser.org",
            "Komodia Inc",
            "Kuaiso Beijing ICP",
            "Laurent Jouanneau",
            "Leiki Ltd",
            "Let's Encrypt",
            "LetSearch.ru",
            "LG",
            "Lightspeed Systems",
            "Linden Labs",
            "Line Corporation",
            "Linkdex Limited",
            "LinkedIn Corporation",
            "Linkfluence SAS",
            "Linkis.com",
            "LinkPad",
            "Linux Foundation",
            "Lipperhey",
            "LogicWare & LSoft Technologies",
            "LongURL.org",
            "ltx71.com",
            "Lucas Ou-Yang",
            "Lucidworks",
            "Lunascape Corporation",
            "Mail.Ru Group",
            "Majestic-12 Ltd",
            "Makoto Kinoshita",
            "Maple Studio",
            "Marc Lehmann",
            "Mark Miller",
            "Marketscore",
            "Marketwire L.P.",
            "Mason Larobina",
            "Maxthon International Limited",
            "MAZ Systems Inc.",
            "Mediatoolkit",
            "MegaIndex.ru",
            "Meizu Technology Co., Ltd.",
            "Meltwater US Inc.",
            "Mesa Dynamics",
            "metauri.com",
            "Michael Dowling",
            "Michael Schoebel",
            "Microsoft Corporation",
            "Mikulas Patocka",
            "Mislav Marohnic",
            "Mixmax, Inc.",
            "Moat, Inc.",
            "Mobicip.com",
            "MobileIron",
            "Mojeek Ltd.",
            "Monitor Backlinks Ltd.",
            "Moonchild Productions",
            "MopoTab Inc",
            "Moreover Technologies, Inc",
            "Motorola",
            "Mozilla Foundation",
            "MSR&Joker",
            "Myriad Group",
            "Nagios Enterprises, LLC.",
            "National Institute of Information and Communications Technology, Japan",
            "National Library of Sweden",
            "Natural Language Processing Group of the University of Leipzig",
            "Netcraft Ltd.",
            "NetEase (Hangzhou) Network Co., Ltd.",
            "netEstate GmbH",
            "NetGate Technologies",
            "Netscape",
            "NetSeer, Inc.",
            "NetTrack",
            "Neustar",
            "News.me Inc",
            "NHN Corporation",
            "Nintendo",
            "No Limit Software",
            "Nokia",
            "Notify Ninja",
            "Novell",
            "NTENT",
            "NTT Resonant Inc.",
            "Nullsoft",
            "Nuzzle Inc",
            "Obigo",
            "Oculus",
            "Omni Development Inc",
            "Online Media Group, Inc.",
            "OpenLink Software",
            "Opera Software ASA",
            "OPPO",
            "Oracle",
            "Orange S.A.",
            "Oregan Networks Ltd",
            "Oscar Otero",
            "otter-browser.org",
            "Overwolf",
            "pagepeeker SRL",
            "Panasonic",
            "Panic Software",
            "Paper.li",
            "Paul Hammond",
            "Paypal",
            "pdrlabs.net",
            "Pearltrees - Broceliand SAS",
            "phantomjs.org",
            "photonproject.net",
            "PingAdmin.ru",
            "Pingdom AB.",
            "Pirate Bay",
            "Pivotal Labs",
            "PlantRob",
            "Poco Systems Inc.",
            "Polychrome Ltd",
            "Postbox, Inc.",
            "Postman, Inc.",
            "POTI Inc",
            "pr-cy.ru",
            "Prismatic",
            "prlog.ru",
            "Profound Networks, LLC",
            "publiclibraryarchive.org",
            "Python Software Foundation",
            "Qihoo 360 Technology Co. Ltd.",
            "Qualidator.com",
            "Quora, Inc.",
            "QWANT SAS",
            "Radical Software Ltd",
            "rambler.ru",
            "rankflex.com",
            "Raptr",
            "Raven Internet Marketing Tools",
            "Raynette",
            "Read It Later, Inc",
            "RebelMouse",
            "Research and Development Unit for English Studies, Birmingham City University",
            "Research In Motion Limited",
            "Richard Trautvetter",
            "riddler.io",
            "Riser Apps LLC",
            "Ritlabs SRL.",
            "Roku, Inc.",
            "Rostelecom",
            "RostPay Ltd",
            "RuanMei.com",
            "Ryan Parman, Geoffrey Sneddon, Ryan McCue and contributors",
            "Ryte GmbH",
            "SafeDNS Inc",
            "Sakamoto Hironori",
            "Salesforce.com, Inc.",
            "Samsung",
            "Schoology",
            "Scrapinghub Limited",
            "scrapy.org",
            "searchme.com",
            "Searchturbo Ltd",
            "Semantic Dimension",
            "semantic-visions.com",
            "semantissimo.de",
            "semasio.com",
            "SEMrush",
            "SentiOne LLC",
            "SEO Cube S.r.l.",
            "SEO Scanners",
            "SEO Site Checkup LLC",
            "seobility GmbH",
            "seodiver.com",
            "SEOmoz",
            "SEOmoz, Inc.",
            "SERAPHIC Information Technology (Shanghai) Co., Ltd.",
            "serpstatbot.com",
            "Seznam.cz, a.s.",
            "Shilyaev Egor",
            "ShrinkTheWeb",
            "Sien",
            "SimilarTech Ltd.",
            "Sina Corporation",
            "Sindice",
            "SISTRIX GmbH",
            "site-shot.com",
            "siteexplorer.info",
            "Siteimprove.com",
            "slack.com",
            "Snap Inc.",
            "Socialrank.io",
            "Software in the Public Interest, Inc.",
            "Sogou Inc",
            "Sohu.com Inc.",
            "Sony",
            "SonyEricsson",
            "Soren Stoutner",
            "Sparrow SARL",
            "SpeedCurve",
            "Spotify AB",
            "SPRINKLR INC.",
            "spyonweb.com",
            "Square, Inc.",
            "SRWare",
            "Stanley Lim",
            "StatusCake",
            "Stefan Burstroem",
            "Stefano Alimonti",
            "Stephan Schmitz",
            "Stewart Smith",
            "StumbleUpon, Inc.",
            "superbird-browser.com",
            "Sur.ly",
            "Syllable Project",
            "Synacor, Inc.",
            "Tapbots, LLC",
            "Taringa.net",
            "Tassaris",
            "team Haxx",
            "Tencent Ltd.",
            "Tenta LLC",
            "Tesla Motors",
            "The Apache Software Foundation",
            "The British Legal Deposit Libraries",
            "the Dillo Project",
            "The Document Foundation",
            "the friendica project",
            "The GNOME Project",
            "The Old Reader",
            "the PHP Group",
            "The Rocket Science Group",
            "TheWorld.cn",
            "ThingLink Oy",
            "Thomas Dickey",
            "Thomas Schulte",
            "thumbnail.ws",
            "Tiscali",
            "Tobit Software AG",
            "Todd Ditchendorf",
            "Torsten Rueckert Internetdienstleistungen",
            "Toutiao",
            "Traackr Inc",
            "Tracemyfile Ltd.",
            "Traffic Names Ltd",
            "trendiction.de",
            "Tumblr, Inc.",
            "Turkcell",
            "Turnitin LLC",
            "Twingly AB",
            "Twitter",
            "ubermetrics-technologies.com",
            "UCWeb Inc.",
            "Unity Technologies",
            "Uptime.com",
            "Valve Corporation",
            "VaporWare",
            "Vebidoo.de",
            "Verisign",
            "VideoLAN non-profit organization",
            "Viderem AB",
            "visionmedia",
            "Vivaldi Technologies",
            "Vivo Global",
            "vk.com",
            "VSI innovation",
            "W3C",
            "Web CEO Limited",
            "Web Design Group",
            "Web Integration IT Service GmbH",
            "webglance.com",
            "Webhose.io",
            "WebMeUp",
            "WeSEE Ltd",
            "WhiteHat Security",
            "WikiApiary",
            "wise-guys.nl",
            "wkhtmltopdf.org",
            "wmtips.com",
            "woorank.com",
            "wordpress.org",
            "www.acoobrowser.com",
            "www.freewebmonitoring.com",
            "www.newsblur.com",
            "www.phpclasses.org",
            "www.vbseo.com",
            "www.waterfoxproject.org",
            "Xavier Grangier",
            "Xavier Roche",
            "XBMC Foundation",
            "Xiaomi Tech",
            "XML Sitemaps",
            "Xovi GmbH",
            "Yahoo! Inc.",
            "Yahoo!JAPAN",
            "Yandex LLC",
            "Yioop!",
            "Yisou.com",
            "yooz.ir",
            "ZaoJianZhen",
            "Zend Technologies Ltd.",
            "Zeta Centauri",
            "Zhihu.com",
            "Zoom Internet Co., Ltd",
            "ZUMinternet Corp",
            "zvu.com"
        ];
    }

    public function get(string $keyword): array
    {
        // TODO: Implement get() method.
    }
}