<?php


namespace Mishusoft\Framework\Chipsets\Http\UserAgents;


use Mishusoft\Framework\Chipsets\Http\UserAgents;

class Vendors extends UserAgents
{

    public function list(): array
    {
        // TODO: Implement list() method.
        return  [
            "3Q",
            "4Good",
            "Acer",
            "Adspec",
            "Advent",
            "Ainol",
            "Alcatel",
            "Alfawise",
            "Amazon.com, Inc.",
            "Amlogic",
            "Apple Inc",
            "Archos",
            "ARK",
            "Arnova",
            "Assistant",
            "Asus",
            "Azumi",
            "Barnes & Noble",
            "Beelink",
            "BlackBerry Limited",
            "BLU",
            "BOMIX",
            "BQ",
            "BrightSign, LLC",
            "Cat Sound",
            "Caterpillar",
            "CCE",
            "Coby",
            "Commodore International",
            "Condor",
            "Coolpad",
            "Cortex",
            "Cube",
            "Cubot",
            "Dell",
            "DEX",
            "Dialog",
            "Digma",
            "DNS",
            "Dream Property GmbH",
            "Essential",
            "Explay",
            "Fairphone",
            "Fly",
            "Foxconn",
            "FREE SAS",
            "Fujitsu",
            "Garmin-Asus",
            "Geniatech",
            "Gigabyte",
            "Gionee",
            "GOCLEVER",
            "Google",
            "Google Inc",
            "Highscreen",
            "Hisense",
            "HP",
            "HTC",
            "HTM",
            "Huawei",
            "iconBIT",
            "Impression",
            "iNew",
            "Infinix",
            "InFocus",
            "Intenso",
            "Irbis",
            "Itel",
            "Jiayu",
            "Jolla Ltd.",
            "KAZAM",
            "Keneksi",
            "Kiano",
            "KTC",
            "Kyocera",
            "Lava",
            "LeEco",
            "Lenovo",
            "LG",
            "Logicom",
            "Lyf",
            "Mecool",
            "Medion",
            "MegaFon",
            "Meizu Technology Co., Ltd.",
            "Micromax",
            "Microsoft",
            "Microsoft Corporation",
            "Minix",
            "Mobistel",
            "MODECOM",
            "Motorola",
            "MSI",
            "MTC",
            "myTAB",
            "Navcity",
            "NEC",
            "Nexbox",
            "NGM",
            "Nintendo",
            "Nokia",
            "Nuqleo",
            "Nvidia",
            "Odys",
            "ONDA",
            "OnePlus",
            "OPPO",
            "Orange S.A.",
            "Overmax",
            "Oysters",
            "Palm",
            "Panasonic",
            "Pantech",
            "Philips",
            "PiPO Technology",
            "PocketBook",
            "Prestigio",
            "Qilive",
            "QMobile",
            "Quanta",
            "Raspberry Pi Foundation",
            "RCA",
            "Research In Motion Limited",
            "Ritmix",
            "Ross&Moor",
            "Samsung",
            "SENSEIT",
            "Sharp Corporation",
            "ShySky",
            "Smarty",
            "Sony",
            "SonyEricsson",
            "Star",
            "Swipe",
            "T-Mobile",
            "Tanix",
            "TCL",
            "Teclast",
            "Tecno",
            "Telefunken",
            "Tesco",
            "Tesla Motors",
            "TeXet",
            "ThL",
            "Toshiba",
            "TrekStor",
            "TWZ",
            "Uuvision",
            "ViewSonic",
            "vivo",
            "Vizio",
            "Vodafone",
            "Voyo",
            "Walton",
            "Weltbild",
            "WeTab GmbH",
            "Wexler",
            "Wiko",
            "Xiaomi Tech",
            "Yota Devices",
            "Yulong Computer",
            "ZOPO",
            "ZTE"
        ];
    }

    public function get(string $keyword): array
    {
        // TODO: Implement get() method.
    }
}