<footer id="footer" class="flex-column">
    <div class="flex-column footer1">
        <div class="flex-group flex-row">
            <div class="flex-column blank">
                <div class="bg1">
                    <div class="bg2"></div>
                </div>
            </div>
            <div class="flex-column company-address">
                <div class="company-address-info">
                    <h4 style="font-size:16px">CONTACT INFO</h4>
                    <div style="font-size:12px;">
                        Everyday is a new day for us and we work really hard to satisfy our customers everywhere.
                        <div style="font-size:12px;width: 100%" >
                    <span>
                        <!--&nbsp;&nbsp;-->
                        <span style="font-weight: bold;font-size: 14px;"><?php use Mishusoft\Framework\Chipsets\Framework;

                            echo Framework::COMPANY_NAME; ?>.</span>
                        <a class="link" style="font-size: 12px;" href="https://goo.gl/maps/awk7LSU9Rex192Dq8" target="_blank" rel="noreferrer">View in map<i class="fa fa-location-arrow"></i></a><br/><!--&nbsp;&nbsp;&nbsp;-->
                        Dhaka Cantonment, Mirpur, Dhaka, Bangladesh-1206</span><br/>
                            <span><i class="fa fa-phone"></i>&nbsp;&nbsp;+880 963-8570830</span><br/>
                            <span id="send-mailto-support-center"><i class="fa fa-envelope"></i>&nbsp;&nbsp;<?php echo Framework::COMPANY_MAIL_LINK; ?></span>&nbsp;&nbsp;
                            <a href="<?php echo BaseURL; ?>support"><i class="fa fa-globe"></i>&nbsp;&nbsp;<?php echo Framework::COMPANY_SUPPORT_LINK; ?></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="flex-column footer" style="padding: 10px;">
        <div class="systemFingurePrint col-lg-plus-12 col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xs-plus-12">
            <a href="<?php echo BaseURL; ?>" target="_blank" class="link text-safe"><?php echo Framework::COMPANY_NAME; ?> © 2014 - <?php echo date('Y');?></a>
        </div>
        <div class="systemFingurePrint col-lg-plus-12 col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xs-plus-12" style="margin-top: 5px;">
            <a href="<?php echo BaseURL; ?>about/terms" target="_blank" class="link text-safe">Terms & Condition </a> |
            <a href="<?php echo BaseURL; ?>about/policy" target="_blank" class="link text-safe">Privacy Policy </a>
        </div>
    </div>
</footer>