<?php

use Mishusoft\Framework\Drivers\Session;
use Mishusoft\Framework\Drivers\View;

if (Session::get('auth')): ?>
    <div class="navbar1 flex-row flex-group" id="navbar1">
        <!--<div class="navbar1-left-nav">
            <?php /*if (isset($this->acl) && $this->acl->permission('admin_access')): */?>
                <?php /*if (isset($menu) && $menu !== false): */?>
                    <?php /*for ($i = 0; count($menu) > $i; $i++): */?>
                        <?php /*$class = '';
                        if (View::getViewId() !== false && $menu[$i]['title'] === View::getViewId()) {
                            $class = 'active';
                        } */?>
                        <a href="<?php /*echo BaseURL . strtolower($menu[$i]['url']); */?>" class="<?php /*echo $class; */?>">
                            <span class="<?php /*echo $menu[$i]['icon']; */?>"></span>&nbsp;&nbsp;<?php /*echo $menu[$i]['title']; */?>
                        </a>
                    <?php /*endfor; */?>
                <?php /*endif; */?>
            <?php /*endif; */?>
        </div>-->

        <div class="navbar1-right-nav">
            <a href="<?php echo BaseURL; ?>"><i class="fas fa-home"></i>Home</a>
            <a href="#"><i class="fab fa-facebook-messenger"></i>Chat</a>
            <a href="#"><i class="fas fa-bell"></i>Log</a>
            <span class="navbar1-dropdown">
                <i class="far fa-user"></i>
                    <?php if (empty(Session::get('first-name'))) {
                        echo ucfirst(preg_replace('/' . APP_USERNAME_PREFIX .
                            '/is', '$1', Session::get('username')));
                    } else {
                        echo Session::get('first-name');
                    } ?>
                    &nbsp;
                <i class="fas fa-chevron-down"></i>

                <div class="navbar1-dropdown-content">
                    <?php if ($this->acl->permission('admin_access')): ?>
                        <a href="<?php echo BaseURL; ?>system">
                            <i class="fas fa-cog"></i> Setting
                        </a>
                        <a href="<?php echo BaseURL; ?>user">
                            <i class="fas fa-home"></i> My Panel
                        </a>
                        <a href="<?php echo BaseURL; ?>user/profile">
                            <i class="fas fa-home"></i> Profile
                        </a>
                    <?php elseif ($this->acl->permission('client_access')): ?>
                        <a href="<?php echo BaseURL; ?>client">
                            <i class="fas fa-home"></i> My Panel
                        </a>
                        <a href="<?php echo BaseURL; ?>client/profile">
                            <i class="fas fa-home"></i> Profile
                        </a>
                    <?php endif; ?>
                    <a href="<?php echo BaseURL; ?>user/logout">
                        <i class="fas fa-sign-out-alt"></i> Logout
                    </a>
                </div>
            </span>
        </div>
    </div>
<?php endif; ?>